### ISSUE TITLE
Need help solving a problem in Stage 2 customization

### ISSUE THREAD

**Issue by hgbosley** [sabrinathai/ExperienceSampler#11]
Hello,
I am a novice programmer so I apologize in advance if this is a stupid question. I am stuck on an issue with data saving using the Google Sheets option. I have followed the directions on the "Stage 2 customization" page of the experience sampler website to have the Experience Sampler app save responses in a google sheet. When I run the app in the Genymotion emulator, and then check the google sheet, it does look like something is getting saved in the sheet (the time stamp and unique key are getting stored) but all of the responses to questions, variable names, and participant ID is not appearing. Here is a link to my "splicedDataset" sheet. 
https://docs.google.com/spreadsheets/d/1ajDssrYo4QTWyHJ1O4mrWBDHK7x0fFhOc_avVNt_sZ0/edit#gid=672540253
I cannot figure out what I need to do differently in order to get the participant ID, variable names, and responses to be stored. They are not appearing in the "database" sheet either. Has anyone else run into this problem?
Thanks!

Hannah

**Comment by sabrinathai** [comment]
Hi Hannah
It might be that some lines needed to record the participant's responses have been commented out, so it is not saving. That might be something I forgot to include in the instructions. Can you check if the following lines in the Stage 3 part of the script have been uncommented.

` if (count == 0) {comparisonResponse = response;}` 
`if (count <= -1) {uniqueRecord = currentQuestion}` 
`else {uniqueRecord=uniqueKey + "_" + currentQuestion + "_" + year + "_" + month + "_" + day + "_" + hours + "_" + minutes + "_" + seconds + "_" + milliseconds;}` 
    `//Save this to local storage` 
    `localStore[uniqueRecord] = response;`

If these lines are commented out, uncomment them. Then your data should be written. 

Sabrina

**Comment by hgbosley** [comment]
Ah! Yes, that was the exact problem -- the recordResponse function was mostly commented it out. I just uncommented and tested it again, and it worked perfectly! Thank you so much Sabrina.
(As a side note, I wanted to say I am finding the experience sampler website, instructions, and code all very helpful and exciting -- thank you so much for making this available!)
