### ISSUE TITLE
Need help troubleshooting notification customization for Android version of Experience Sampler

### ISSUE THREAD

**Issue by hgbosley** [sabrinathai/ExperienceSampler#13]
Hello,

I am trying to customize the Experience Sampler app for a signal-contingent design with random intervals. On the Android version, the app runs, and I was able to get the app onto two friends' Android phones, however, they have not received any notifications (though they can go to the app to complete the survey at will and everything else appears to be functioning). I am not getting any errors from debugging the app, so I don't know exactly what the problem is. Has anyone else encountered this problem? 

Thanks for any thoughts/advice!

Hannah

**Comment by sabrinathai** [comment]
Hi Hannah,

I haven't heard of anyone having this problem recently. If you feel comfortable posting the notification portion of your index.js code here, I can see if there is a problem. Or you can send me an email and I can provide you with more instructions on how I can help you out. 

Cheers,
Sabrina

**Comment by hgbosley** [comment]
Thank you so much, Sabrina! I am pasting the relevant part below (please let me know if email is preferred):

scheduleNotifs: function () {
        //cordova.plugins.backgroundMode.enable(); 
        //Section 1 - Declaring necessary variables
        //Declares the number of intervals between the notifications for each day (i.e., if beeping participants 6 times, declare 6 intervals)
        var interval1, interval2, interval3, interval4;

        //Declares a variable to represent the id of each notification for the day
        //Declare as many letters as you have intervals (i.e., 6 intervals, declare 6 ids)
        var a, b, c, d;

        //Declare a variable to represent new date to be calculated for each beep
        //That is, if there are 6 intervals, declare 6 new dates
        var date1, date2, date3, date4;

        //The statement below declares the start and end time of the daily data collection period
        //These variables are not necessary if the start and end time of the daily data collection period do not vary across the experience
        //sampling data collection period
        var currentMaxHour, currentMaxMinute, currentMinHour, currentMinMinute, nextMinHour, nextMinMinute;

        //The next three lines create variables for the present time when the notifications are being scheduled
        var dateObject = new Date();
        var now = dateObject.getTime();
        var dayOfWeek = dateObject.getDay(), currentHour = dateObject.getHours(), currentMinute = dateObject.getMinutes();

        // 		//The next variables represent the amount of time between the end of the data collection to the start of the next one (nightlyLag), 
        // 		//the interval between the scheduling time and the start of the first data collection period (currentLag), the maximum amount of time
        // 		//in the data collection period (maxInterval), and the time  until the end of the next data collection period (in our case 
        // 		//dinner time; dinnerInterval)
        var nightlyLag, currentLag, maxInterval, dinnerInterval;

        // 		//These represents the participants time values 
        var weekendSleepTime = localStore.weekendSleepTime.split(":");
        var weekendWakeTime = localStore.weekendWakeTime.split(":");
        var weekdaySleepTime = localStore.weekdaySleepTime.split(":");
        var weekdayWakeTime = localStore.weekdayWakeTime.split(":");

        // 		//Then you can declare any values that you might use more than once such as the number of milliseconds in a day
        var day = 86400000;
        var minDiaryLag = 14400000;
        var randomDiaryLag = 1800000;
        var minDiaryLagAfterSleep = 3600000;

        // 		//This is a loop that repeats this block of codes for the number of days there are in the experience sampling period
        // 		//Replace X with the number of days in the experience sampling period (e.g., collecting data for 7 days, replace X with 7)
        // 		//Note that iOS apps can only have 64 unique notifications, so you should keep that in mind if you are collecting data 
        // 		//for more than longer periods of time
        for (i = 0; i < 30; i++) {
            //The code below (up to "else { nightlyLag = ...}" is only necessary if you allow the daily data collection period to vary across 
            //weekdays and weekends
            var alarmDay = dayOfWeek + 1 + i;
            if (alarmDay > 6) { alarmDay = alarmDay - 7; }
            // enter time weekendSleepTime hour and then enter weekendSleepTime minute
            if (alarmDay > 6) { alarmDay = alarmDay - 7; }
            if (alarmDay == 0 || alarmDay == 6) {
                currentMaxHour = weekendSleepTime[0];
                currentMaxMinute = weekendSleepTime[1];
                currentMinHour = weekendWakeTime[0];
                currentMinMinute = weekendWakeTime[1];
                if (alarmDay == 0) {
                    nextMinHour = weekdayWakeTime[0];
                    nextMinMinute = weekdayWakeTime[1];
                }
                else {
                    nextMinHour = weekendWakeTime[0];
                    nextMinMinute = weekendWakeTime[1];
                }
                currentLag = (((((24 - parseInt(currentHour) + parseInt(weekendWakeTime[0])) * 60) - parseInt(currentMinute) + parseInt(weekendWakeTime[1])) * 60) * 1000);

            }
            else {
                currentMaxHour = weekdaySleepTime[0];
                currentMaxMinute = weekdaySleepTime[1];
                currentMinHour = weekdayWakeTime[0];
                currentMinMinute = weekdayWakeTime[1];
                if (alarmDay == 5) {
                    nextMinHour = weekendWakeTime[0];
                    nextMinMinute = weekendWakeTime[1];
                }
                else {
                    nextMinHour = weekdayWakeTime[0];
                    nextMinMinute = weekdayWakeTime[1];
                }
                currentLag = (((((24 - parseInt(currentHour) + parseInt(weekdayWakeTime[0])) * 60) - parseInt(currentMinute) + parseInt(weekdayWakeTime[1])) * 60) * 1000);
            }
            if (alarmDay == 5 || alarmDay == 0) { nightlyLag = currentLag; }
            else {
                nightlyLag = (((((24 - parseInt(currentHour) + parseInt(nextMinHour)) * 60) - parseInt(currentMinute) + parseInt(nextMinMinute)) * 60) * 1000);
            }



            //The maxInterval is the number of milliseconds between wakeup time and sleep time
            maxInterval = (((((parseInt(currentMaxHour) - parseInt(currentMinHour)) * 60) + parseInt(currentMaxMinute) - parseInt(currentMinMinute)) * 60) * 1000);
            //This part of the code calculates how much time there should be between the questionnaires
            //Change X to the minimum amount of time that should elapse between beeps in seconds
            //Change Y to the amount of additional time in seconds that should elapse to reach the maximum amount of time
            //The part of the code that accompanies Y randomly generates a number that allows for notifications to occur randomly between X and X+Y after the previous beep
            //That is, X + Y = maximum amount of time that can elapse between beeps
            // 
            // If designing an interval-based design, delete "Math.round(Math.random()*Y)+" and replace X with the amount of 
            // time in seconds between each beep

            interval1 = (((parseInt(nightlyLag) + parseInt(3600)) * 1000) + ((parseInt(86400) * parseInt(i)) * 1000));
            interval2 = (interval1 + ((parseInt(Math.round(Math.random() * 3600) + 12600)) * 1000));
            interval3 = (interval2 + ((parseInt(Math.round(Math.random() * 3600) + 12600)) * 1000));
            interval4 = (interval2 + ((parseInt(Math.round(Math.random() * 3600) + 12600)) * 1000));
            SleepInterval = parseInt(currentLag) + parseInt(maxInterval) + (parseInt(86400000) * parseInt(i));

            //    
            // 			//This part of the code calculates a unique ID for each notification     
            a = 101 + (parseInt(i) * 100);
            b = 102 + (parseInt(i) * 100);
            c = 103 + (parseInt(i) * 100);
            d = 104 + (parseInt(i) * 100);


            //
            // 			//This part of the code calculates the time when the notification should be sent by adding the time interval to the current date and time        
            date1 = new Date(now + interval1);
            date2 = new Date(now + interval2);
            date3 = new Date(now + interval3);
            date4 = new Date(now + interval4);


            //         
            // 			//This part of the code schedules the notifications
            cordova.plugins.notification.local.schedule([
                { icon: 'ic_launcher', id: a, at: date1, text: 'Time for your next Survey!', title: 'Diary Surveys' },
                { icon: 'ic_launcher', id: b, at: date2, text: 'Time for your next Survey!', title: 'Diary Surveys' },
                { icon: 'ic_launcher', id: c, at: date3, text: 'Time for your next Survey!', title: 'Diary Surveys' },
                { icon: 'ic_launcher', id: d, at: date4, text: 'Time for your next Survey!', title: 'Diary Surveys' },]);

            //This part of the code records when the notifications are scheduled for and sends it to the server
            localStore['notification_' + i + '_1'] = localStore.participant_id + "_" + a + "_" + date1;
            localStore['notification_' + i + '_2'] = localStore.participant_id + "_" + b + "_" + date2;
            localStore['notification_' + i + '_3'] = localStore.participant_id + "_" + c + "_" + date3;
            localStore['notification_' + i + '_4'] = localStore.participant_id + "_" + d + "_" + date4;

        }
    }

**Comment by sabrinathai** [comment]
Everything looks good! Why don't you send me an email (sabrina.thai@mail.mcgill.ca)?

**Comment by sabrinathai** [comment]
Hi Hannah,

So the problem was that even though your scheduleNotif function is perfect, you didn't execute it anywhere in the script. In our original app, we execute the scheduleNotif function once participants complete the participant setup questions. This line is in the question logic portion of the study. Because you had no logic, you skipped this whole section. I just commented the line that executes this function. Thanks for bringing this to my attention! I will have to update the instructions to reflect this. 

We set the app to record all the notification times in case there is a problem the notifications during the data collection period. It is also a way to let us know that the notifications have been scheduled, and if you are interested, you can also calculate response latencies from the recorded notification times. 

If you choose to write all this data, Android devices don't like it. However, we recently learned that we can now use the `doPost` method in our Google Script Data Collector. This should allow you to write more data without any data loss, but we need to test this more extensively. So you can just change the first line of your Google Data Collector from `doGet` to `doPost`. Remember also to change the saveData functions type from `get` to `post`. 

Another thing I learnt was that you can't schedule notifications and then move directly into the survey questions. When I tried to do this, the app wouldn't write any data at the end. 

Thanks so much for posting your question! I'm sure this question will be helpful to everyone!
