### ISSUE TITLE
App hangs when setup is complete on iOS only. 

### ISSUE THREAD

**Issue by monkeysailor** [sabrinathai/ExperienceSampler#14]
Hi,
I'm having a problem that the experience sampler app is hanging when it tries to send data to the google script. The app works fine in Browser & Android versions, but hangs on iOS, both with a physical device and with an emulated one. I'm suspecting this might be something to do with whitelisting, but I can't seem to nail the problem down. Any suggestions?

Thanks

**Comment by sabrinathai** [comment]
When you say hanging, do you mean it just sits on the send data page and doesn't advance?

**Comment by monkeysailor** [comment]
Yes, it gets as far as running the savedata function, but it doesn't return from the ajax call, it just sits there with the "Please wait while the data is sent to our servers..." message displayed. I tried to dump console text on success or fail, but neither happens. It just gets into saveDataLastPage, to the point of sending the ajax, and sulks. As I say, it works fine in Browser and Android.

**Comment by sabrinathai** [comment]
Did you use the JSON.stringify function on the localStore?

**Comment by monkeysailor** [comment]
You are a steely-eyed code monster, and I salute you! I hadn't. Well spotted.
