### ISSUE TITLE
Question on customization

### ISSUE THREAD

**Issue by greggrs** [sabrinathai/ExperienceSampler#15]
Hello,

I had a question about the app's customization (I looked over the website but couldn't find the answer): What is the default personal/contact information collected by Experience Sampler (if any) that is necessary for someone to install and use the app? Can this be changed?

I'm asking because I'd like to use Experience Sampler for a study posted on MTurk. But Mturk's ToS doesn't want requesters to ask for _any_ contact information. Other experience sampling apps tend to ask for either for a phone number, email address or some other contact information (so they violate the ToS). Can Experience Sampler be used without collecting any contact information? Could I, for example, just randomly assign someone a participant ID and then the app keeps track of the participant's ID and logs that info whenever they respond to a survey (so that the participant never has to enter their ID, but their responses across surveys are recorded and associated with each other)?

Thanks!!

**Comment by sabrinathai** [comment]
Hello,

You don't need to collect any default personal/contact information at all. The app can be used without any personal/contact information. You just won't be able to use our compliance reminder email system. 

You can randomly assign a Participant ID to an MTurk worker. The only problem is if your participant payment is contingent upon degree of completion (i.e., how many surveys they complete), then you can't link the participant's responses to their ID.
