### ISSUE TITLE
issues with adding plugins

### ISSUE THREAD

**Issue by svddatta** [sabrinathai/ExperienceSampler#19]
hey all,

having trouble with just the last plug in command below:
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#ios10

error message is:
Error: Current working directory is not a Cordova-based project.

I confirmed that the cd PATH command was putting files into the correct (Cordova-based project) folder. Any thoughts?

:)

**Comment by sabrinathai** [comment]
Try the following instead: 
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#x 

as suggested by Sean Aubin.

**Comment by svddatta** [comment]
hmmm getting this:

Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-local-notifications#x via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

**Comment by sabrinathai** [comment]
Maybe try this
cordova plugin add de.appplant.cordova.plugin.local-notification
