### ISSUE TITLE
Issue with iOS version

### ISSUE THREAD

**Issue by squeekur** [sabrinathai/ExperienceSampler#2]
Greetings Ladies, I sent Elizabeth an email but I received an auto-reply. Without a better way to reach you I guess I have to post this as an issue.  I'm getting errors in Xcode from the katzer plugins and was hopeful you could suggest alternatives to background-mode and local-notification.

**Comment by sabrinathai** [comment]
Hi squeekur, Sorry, we don't have any other alternatives to recommmend. These plugins are the most commonly used ones and the most reliable. I think you will just have to wait for the issue to be resolved. Someone has already posted it as an issue for the katzer plugin (https://github.com/katzer/cordova-plugin-local-notifications/issues/910).
