### ISSUE TITLE
Estimation of workload?

### ISSUE THREAD

**Issue by vincentbeermann** [sabrinathai/ExperienceSampler#20]
Hello!

Currently we are planning a simple (only participant's response to questionnaires are relevant) ESM study. The study consists out of 5 items (closed and open questions), 5 prompts, 7 days. We would like to run the study on both Android and iOS.

Because we are on a tight schedule we have to decide now whether we use the Experience Sampler or ready-to-use ESM software. 
We would like to know how much workload it takes to program such app from start to finish. We obtained a B.Sc./M.Sc. in Psychology, but don't have very much experience in programming. Could someone provide a rough estimation of how much working hours it takes? <25h, <50h, <100h, <100h?

Thank you very much for any helpful information.

Best,
Vincent

**Comment by sabrinathai** [comment]
Hi Vincent,

I would estimate somewhere between <25 to <50. 
But closer to <25. 

Cheers,
Sabrina
