### ISSUE TITLE
Adding audio/image/video responses?

### ISSUE THREAD

**Issue by anshul1516** [sabrinathai/ExperienceSampler#27]
Hi Team Experience Sampler!
I was wondering what would be the easiest way to:

1. integrate voice/photo/video responses to a prompt.
e.g. "Could you share what your environment looks like right now?"

2. Track participant location.

**Assumptions I'm making here:**
Using a web server to store the responses(audio/image/video file).
Consent from participants for both location and any sort of audio/visual data has been received.

I can experiment with implementing the code. Just need some pointers on what classes/plugins do I need to add onto this build.

Thanks!

**Comment by sabrinathai** [comment]
You should contact Chao Zhang at Eindhoven University for information about how to incorporate sound and pictures into ExperienceSampler. I'm not sure whether Chao has figured out how to incorporate video, but I do know he has figured out how to incorporate sound and photos.
