### ISSUE TITLE
Issues with Scheduling for Second Set of Notifications

### ISSUE THREAD

**Issue by bizerkmaverick** [sabrinathai/ExperienceSampler#28]
Good evening,

I am having issues with trying to schedule a second set of notifications based on the time selected during the participant setup. The notifications are scheduled correctly for the first notification function `scheduleNotifs:function() {` however when I try implement the same code into the second schedule notifications function  `scheduleNotifs2:function() {` I get a blank screen after dismissing the alert saying, "Your questions will load shortly. Please wait while we schedule your notifications for the next week." 

The code added to `participantSetup`
```
{
"type": "timePicker",
"variableName": "wakeTime",
"questionPrompt": "Please select the time that you usually wake up:"
},
```

The code added to `scheduleNotifs:function() {`
```
var wakeTime = localStore.wakeTime.split(":");
var hh = wakeTime[0];
var mm = wakeTime[1];
```

Code changed from `var startTime = startDate.setHours(8,0,0,0);` to `var startTime = startDate.setHours(parseInt(hh),parseInt(mm)+30,0,0);`

The final variable to set the start time for the next day based on the previous variables
`var nextDiaryLag = ((parseInt(startTime) - parseInt(now))+ (1000 * 60 * 60 * 24));`

This all works correctly but when adding this same code to `scheduleNotifs2:function() {`
```
var wakeTime = localStore.wakeTime.split(":");
var hh = wakeTime[0];
var mm = wakeTime[1];
var startTime = startDate.setHours(parseInt(hh),parseInt(mm)+30,0,0);
var nextDiaryLag = ((parseInt(startTime) - parseInt(now))+ (1000 * 60 * 60 * 24));
```
A blank screen appears when opening the app to schedule the next set of notifications.

The second set of notifications scheduled normally before attempting to add this code. I've tried renaming the variables in the second notifs functions and adding the second notifs function to the question logic which did not seem to change anything. Any advice or suggestions would be greatly appreciated. 
I have attached the .js file for review as well.
[5.24.18index.zip](https://github.com/sabrinathai/ExperienceSampler/files/2034347/5.24.18index.zip)

Thanks for all the help,
Erick

**Comment by bizerkmaverick** [comment]
Good evening,

I wanted to give a minor update. I tried implementing the iOS code above into Android and trying to test what is wrong. I used the Google Chrome web browser to inspect the blank screen when the second set of notifications are meant to be scheduled. It gave me the follow error:
`index.js:725 Uncaught TypeError: Cannot read property 'split' of undefined`
for this line of code:
`var wakeTime = localStore.wakeTime.split(":");` inside the `scheduleNotifs2` function

What I can't figure out is why that same line of code for the `scheduleNotifs` function works correctly and is able to use the data saved for the wake time during participant setup but the `scheduleNotifs2` function can't find or is unable to use the stored values.

I tried a few different lines of code to try and fix this:
	Attempt 1:
```
		var wakeTime = localStore.wakeTime
		var wakeTime1 = wakeTime.split(":");
		var hh = wakeTime1[0];
		var mm = wakeTime1[1];
```
Attempt 2:
`var wakeTime = participantSetup.wakeTime.split(":");`
	Attempt 3:
`		var wakeTime = participantSetup.localStore.wakeTime.split(":");`
	Attempt 4:
`		var wakeTime = localStore.participantSetup.wakeTime.split(":");`
	Attempt 5:
`		var wakeTime = localStore.wakeTime;`

but they all ended up with similar errors.

If anyone is able to help or provide some suggestions, I would greatly appreciate it.
I have also attached the android js file for review as well.
[5.31.18index.zip](https://github.com/sabrinathai/ExperienceSampler/files/2061197/5.31.18index.zip)

Thanks,
Erick

**Comment by sabrinathai** [comment]
It sounds like you are not storing your wake time in local store after the app is installed and setup for the first time, so when you try to schedule the second set of notifications using the wake time, the app cannot do this.

To resolve this in you `saveDataLastPage` and `saveData` functions, you need to save wake time.

So **before** the line `localStore.clear();` in both functions, you need to add `var wakeTime = localStore.wakeTime;`

And then **after** the line `localStore.clear();` in both functions, you need to add `localStore.wakeTime = wakeTime;`

I think this should solve your problem.

**Comment by bizerkmaverick** [comment]
This fixed the issue. Thanks so much for your help!
