### ISSUE TITLE
scheduleNotifs function not scheduling correctly

### ISSUE THREAD

**Issue by WHIRLab** [sabrinathai/ExperienceSampler#54]
Hello,

I am having a problem getting the notifications to schedule correctly for my iOS app. I am trying to have the app send a notification at 7:00 pm every day for seven days, but the notifications are instead being scheduled every day for whatever time it is when I complete the participant setup questions. That is, if I send through the setup questions at 10:00 am, the app will notify me at 10:00 every day for a week. I'm including the relevant code below; I would appreciate any help with getting the notifications scheduled correctly!

I am also wondering if it is possible to lock the survey after the sampling period has passed (I would like to allow participants to take the survey from 7:00-midnight each night).

Thank you, we are looking forward to using this app!

scheduleNotifs:function(){
 	var notifs=[];
	var interval;
	var a;
 	var date1;
	var nextDiaryLag
	var day = 86400000; 
	var now = new Date().getTime();
	var startDate = new Date();
 	var startDay = startDate.getDate();
	var startTime = startDate.setDate((startDay+1), 19,0,0,0);
	nextDiaryLag = parseInt(startTime) - parseInt(now);

for (i = 0; i < 7; i++){
 interval = nextDiaryLag + day*i;
	date1 = new Date(now + interval);
	a = 101+(parseInt(i)*100);
	notifs.push({id: a, at: date1, text: 'Time for your next Diary Survey!', title: 'Diary Surveys'});

localStore['notification_' + i + '_1'] = localStore.participant_id + "_" + a + "_" + date1; 
}
    cordova.plugins.notification.local.schedule(notifs);
},

snoozeNotif:function() {
    var now = new Date().getTime(), snoozeDate = new Date(now + 1800*1000);
    var id = '99';
    cordova.plugins.notification.local.schedule({
                                         id: id,
                                         title: 'WHIRLab Survey',
                                         text: 'Please complete your daily survey now!',
                                         at: snoozeDate,
                                         });
},

**Comment by JamesNewey** [comment]
This line is storing the UTC datetime in the now variable:
`var now = new Date().getTime();`
This is the number of milliseconds between January 1, 1970, 00:00:00 and the time of asking.
The Date constructor here is then adding 1-7 to this value 7 times:
`date1 = new Date(now + interval);`
This means that date1 date will be 1-7 milliseconds further forward than the now date.
To add days to a date I would follow [this example](https://stackoverflow.com/questions/3818193/how-to-add-number-of-days-to-todays-date)

**Comment by WHIRLab** [comment]
Thank you @JamesNewey!
