### ISSUE TITLE
 cordova plugin add de.appplant.cordova.plugin.background-mode fails

### ISSUE THREAD

**Issue by hakanjonsson** [sabrinathai/ExperienceSampler#7]
Adding background plugin using 
`cordova plugin add de.appplant.cordova.plugin.background-mode`
fails with the message 
`Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.plugin.background-mode`
Using `cordova plugin add cordova-plugin-background-mode` work fine though, but not sure if anything else needs to be changed in instructions or example code with this new plugin id.

**Comment by sabrinathai** [comment]
Thanks for bringing this to my attention! ExperienceSampler no longer needs the background mode plugin to operate! I will update the instructions.
