### ISSUE TITLE
cordova android run fails

### ISSUE THREAD

**Issue by hakanjonsson** [sabrinathai/ExperienceSampler#9]
According to the instructions, `cordova android run ` should be used to build and launch the app in the emulator. However, running this command results in the following error message:
"Error: Cordova does not know android; try `cordova help` for a list of all the available commands."

**Comment by sabrinathai** [comment]
Thank you for bringing this typo to our attention. The correct command should be `cordova run android`.  I have updated the instructions. Also be sure to update the path of the keystore file before running this command. The instructions to do so can be found [here](http://experiencesampler.com/distribution.html#manual-signing).

**Comment by hakanjonsson** [comment]
Thanks, but I should still be able to create debug versions without signing, and they would still work, right?

**Comment by sabrinathai** [comment]
Yes! You should, but to run the Example ExperienceSampler app, I think you would have to remove the **release-signing.properties** file, which has the location of the keystore in it, and can be found in the `platform/android` folder. Then you should be able to run debug versions.
